name: Upload to Azure Blob Storage

on:
  push:
    branches: [ main ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Azure CLI Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Upload files to blob storage 
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload-batch --account-name prjazresume -d '$web'  -s ./frontend

      - name: Purge CDN endpoint
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az cdn endpoint purge --content-paths "/*" --profile-name "azresumecdn" -n "azresumecdnendpoint" -g "rg_azresume"
            
      - name: logout
        run: |
              az logout
            
